[package]
name = "cloudkit-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
cloudkit-proto = { path = "../cloudkit-proto" }
deluxe = "0.5.0"
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = "2.0.100"
